version: "3.9"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "10000:10000"
    env_file:
      - .env.docker
    depends_on:
      - db
    volumes:
      - .:/app 

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: