"""Added index to product table

Revision ID: 179dfb2e8c78
Revises: 93bd3ca13d08
Create Date: 2026-01-12 20:46:57.886418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179dfb2e8c78'
down_revision: Union[str, Sequence[str], None] = '93bd3ca13d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.create_index('idx_owner_id', 'product', ['owner_id'], unique=False)
    op.create_index('idx_product_name', 'product', ['name'], unique=False)
    op.create_foreign_key(None, 'product', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_user_email'), table_name='users')
    op.drop_index(op.f('ix_user_id'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_user_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_user_email'), 'users', ['email'], unique=True)
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_index('idx_product_name', table_name='product')
    op.drop_index('idx_owner_id', table_name='product')
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.drop_column('product', 'owner_id')
    # ### end Alembic commands ###
