"""Added timestamp columns in product table

Revision ID: 580d841fada0
Revises: 179dfb2e8c78
Create Date: 2026-01-12 23:00:56.615251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '580d841fada0'
down_revision: Union[str, Sequence[str], None] = '179dfb2e8c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('product', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'updated_at')
    op.drop_column('product', 'created_at')
    # ### end Alembic commands ###
